#pragma once

typedef enum option {
	LOOK_AROUND, FEEL_WALL, SCREAM_FOR_HELP,
	RUN_RAND, LOOK_HARDER, KEEP_FEELING, FEEL_OTHER, RUN_TOWARDS, RUN_AWAY, KEEP_SCREAMING,
	GANDALF_BATTLE, GANDLAF_RUN, SWITCH_ON, SWITCH_OFF, GO_HOME, LOOK_FOR_VICTIMS,
    CALL_POLICE, CALL_MOM, HONORIFICABILITUDINITATIBUS, DANCE, PICK_PHONE, LEAVE_PHONE,
	TROLL_BATTLE, TROLL_PHONE, PHONE_REVERSE, WAIT_DAYS, 
	FOLLOW_POTTER, TROLL_STEAL, EPIC_QUEST, CALCULATOR, INSPECT_WELL, INSPECT_BACKYARD, 
	PROVE_GOD, ATTACK_GOD, TEST_YOUR_LUCK, TROLL_WEAR, PLAY_CLUB,
	ISLAND_TUNNEL, ISLAND_SHIP, ISLAND_AIRSHIP, KILL_HERO, EXPLAIN_HERO,
	KEEP_DIGGING, DIG_UP, MASSACRE, EAT_HERO,
	MORE_DIGGING, SHARK_JUMP, SHARK_TANK
}OPTION;