#pragma once

typedef enum option {
	LOOK_AROUND, FEEL_WALL,
	RUN_RAND, LOOK_HARDER, KEEP_FEELING, FEEL_OTHER,
	GANDALF_BATTLE, GANDLAF_RUN, SWITCH_ON, SWITCH_OFF,
    CALL_POLICE, CALL_MOM, HONORIFICABILITUDINITATIBUS, DANCE,
	TROLL_BATTLE, TROLL_PHONE,
	FOLLOW_POTTER, TROLL_STEAL, EPIC_QUEST, CALCULATOR,
	SHIP_CABIN, JUMP_OCEAN, TROLL_WEAR, PLAY_CLUB
}OPTION;