#pragma once

typedef enum option {
	LOOK_AROUND, FEEL_WALL,
	RUN_RAND, LOOK_HARDER, KEEP_FEELING, FEEL_OTHER,
	GANDALF_BATTLE, GANDLAF_RUN, SWITCH_ON, SWITCH_OFF,
    CALL_POLICE, CALL_MOM, HONORIFICABILITUDINITATIBUS, DANCE,
	TROLL_BATTLE, TROLL_PHONE,
	FOLLOW_POTTER, TROLL_STEAL, EPIC_QUEST, CALCULATOR,
	PROVE_GOD, ATTACK_GOD, TEST_YOUR_LUCK, TROLL_WEAR, PLAY_CLUB,
	ISLAND_TUNNEL, ISLAND_SHIP, ISLAND_AIRSHIP, KILL_HERO, EXPLAIN_HERO,
	KEEP_DIGGING, DIG_UP, MASSACRE, EAT_HERO,
	MORE_DIGGING, SHARK_JUMP, SHARK_TANK
}OPTION;